### ISSUE TITLE
Вопрос по коду из видео к ДЗ № 6

### ISSUE THREAD

**Issue by lowerKamaCase** [lowerKamaCase/TopPostsQuestion#1]
https://github.com/lowerKamaCase/TopPostsQuestion/blob/5de24a3281508cf9630bf833faa03bfb3a8126af/app.js#L78-L81
Этот вопрос в субботу обсуждали после пары.
В app.js (код переписан с видео к уроку) закомментировал строки 78-81 (проверка на нулевой индекс) и перемещение все равно работает при лайках. Ссылка для проверки - https://lowerkamacase.github.io/TopPostsQuestion/index.html

Получается эта проверка избыточная?

**Comment by coursar** [comment]
Да
