### ISSUE TITLE
Форма добавления должна быть с предыдущих лекций

### ISSUE THREAD

**Issue by coursar** [lowerKamaCase/TopPostsQuestion#2]
https://github.com/lowerKamaCase/TopPostsQuestion/blob/5de24a3281508cf9630bf833faa03bfb3a8126af/app.js#L9-L13

**Comment by lowerKamaCase** [comment]
Это я просто переписал код с вашего видео к шестому уроку.
Сама домашка здесь - https://github.com/lowerKamaCase/TopPostsHomework
Issue там тоже есть - https://github.com/lowerKamaCase/TopPostsHomework/issues/1
Форма добавления в домашке учитывает тип поста.
